eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8084
spring:
  application:
    name: security-service
  datasource:
    initialization-mode: always
    password: rootroot
    platform: mysql
    url: jdbc:mysql://localhost:3306/security_management
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
    show: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: userId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          deserializer:
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer
          json:
            trusted:
              packages: com.securityservice.event
            type:
              mapping: event:com.securityservice.event.QuoteAcceptedEvent
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    template:
      default-topic: userTopic